# Generated by Django 2.0.3 on 2018-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
